### ISSUE TITLE
Unable to select stars

### ISSUE THREAD

**Issue by mkaarthick** [kanytu/custom-rating-bar#1]
Scroll works but unable to select stars in this branch https://github.com/kanytu/custom-rating-bar/blob/scrollview_fix/src/main/java/com/poliveira/apps/CustomRatingBar.java

**Comment by kanytu** [comment]
I've update the code. Could you try again please? 66dcc386201e7cefc690e4a959acb6bf38a26247

**Comment by mkaarthick** [comment]
its working now. Thanks!
